name: ai4edu
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - altair=5.0.1
  - annotated-types=0.6.0
  - anyio=4.6.2
  - arrow-cpp=19.0.0
  - attrs=24.3.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.11.212
  - blas=1.0
  - blinker=1.9.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - cachetools=5.5.1
  - certifi=2025.1.31
  - charset-normalizer=3.3.2
  - click=8.1.7
  - distro=1.9.0
  - expat=2.6.4
  - freetype=2.12.1
  - gflags=2.2.2
  - gitdb=4.0.7
  - gitpython=3.1.43
  - glog=0.5.0
  - h11=0.14.0
  - httpcore=1.0.2
  - httpx=0.27.0
  - icu=73.1
  - idna=3.7
  - jinja2=3.1.6
  - jiter=0.6.1
  - jpeg=9e
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.12.1
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgrpc=1.62.2
  - libmpdec=4.0.0
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libssh2=1.11.1
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=3.0.2
  - mdurl=0.1.0
  - ncurses=6.4
  - numexpr=2.10.1
  - numpy=2.2.2
  - numpy-base=2.2.2
  - openai=1.60.1
  - openjpeg=2.5.2
  - openssl=3.0.16
  - orc=2.0.1
  - packaging=24.2
  - pandas=2.2.3
  - pillow=11.1.0
  - pip=25.0
  - protobuf=4.25.3
  - pyarrow=19.0.0
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pydeck=0.9.1
  - pygments=2.15.1
  - pysocks=1.7.1
  - python=3.13.2
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python_abi=3.13
  - pytz=2024.1
  - pyyaml=6.0.2
  - re2=2022.04.01
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.3
  - rich=13.9.4
  - rpds-py=0.22.3
  - s2n=1.3.27
  - setuptools=72.1.0
  - six=1.16.0
  - smmap=4.0.0
  - snappy=1.2.1
  - sniffio=1.3.0
  - sqlite=3.45.3
  - streamlit=1.42.0
  - streamlit-local-storage=0.0.25
  - tbb=2021.8.0
  - tenacity=9.0.0
  - tk=8.6.14
  - toml=0.10.2
  - toolz=1.0.0
  - tornado=6.4.2
  - tqdm=4.67.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - urllib3=2.3.0
  - utf8proc=2.6.1
  - watchdog=4.0.2
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - Werkzeug
